"""create racer cruiser relationship

Revision ID: 3fec705a233b
Revises: 06419385c01c
Create Date: 2025-03-17 18:13:37.007331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fec705a233b'
down_revision: Union[str, None] = '06419385c01c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cruisers', ['racer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cruisers', type_='unique')
    # ### end Alembic commands ###
