"""updated env for cruiser

Revision ID: 5a6fcff9e18f
Revises: cd44b0d75a74
Create Date: 2025-03-17 14:34:30.582275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6fcff9e18f'
down_revision: Union[str, None] = 'cd44b0d75a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cruisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('power_source_id', sa.Integer(), nullable=False),
    sa.Column('propulsion_id', sa.Integer(), nullable=False),
    sa.Column('handling_id', sa.Integer(), nullable=False),
    sa.Column('total_rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['handling_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['power_source_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['propulsion_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cruisers')
    # ### end Alembic commands ###
