"""Initial migration

Revision ID: 843365004ce6
Revises: 0c5072bc910c
Create Date: 2025-03-02 10:03:48.847536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843365004ce6'
down_revision: Union[str, None] = '0c5072bc910c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credits_first', sa.Integer(), nullable=False),
    sa.Column('credits_second', sa.Integer(), nullable=False),
    sa.Column('credits_third', sa.Integer(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('racers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rank_id', sa.Integer(), nullable=True),
    sa.Column('races_attended', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('racers')
    op.drop_table('ranks')
    # ### end Alembic commands ###
