"""add parts and categories

Revision ID: d245241ff8f4
Revises: e90d1b164d99
Create Date: 2025-03-06 14:34:05.911447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd245241ff8f4'
down_revision: Union[str, None] = 'e90d1b164d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('parts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parts_category_id'), 'parts', ['category_id'], unique=False)
    op.create_foreign_key(None, 'parts', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_index(op.f('ix_parts_category_id'), table_name='parts')
    op.drop_column('parts', 'category_id')
    op.drop_column('categories', 'created')
    # ### end Alembic commands ###
