"""Add unique constraint to Racer name

Revision ID: d827cda913b5
Revises: 843365004ce6
Create Date: 2025-03-03 14:47:08.383483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd827cda913b5'
down_revision: Union[str, None] = '843365004ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ranks', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ranks', type_='unique')
    # ### end Alembic commands ###
