"""update crud with racerupdate

Revision ID: fe96ad65e3e6
Revises: ddd54d48a130
Create Date: 2025-03-03 15:49:00.455476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe96ad65e3e6'
down_revision: Union[str, None] = 'ddd54d48a130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
